spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orgManagement
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  application:
    name: orgmanagementservice