server:
  port: 8788

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xaviontt/soa-configs
          clone-on-start: true
          default-label: main
  security:
    user:
      name: test
      password: test