server:
  port: 8788
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: password
    key-alias: soa
    key-store-type: pkcs12

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          username: ${GIT_CONFIG_USERNAME}
          password: ${GIT_CONFIG_PASS}